// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtOZH0YZroH6cZu3RYBF8PlvQYAJqR30g',
    appId: '1:818820526373:web:4476d637e96e0f56ac2acc',
    messagingSenderId: '818820526373',
    projectId: 'notes-app-48cb7',
    authDomain: 'notes-app-48cb7.firebaseapp.com',
    storageBucket: 'notes-app-48cb7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq4f0LuTUCiWOm_5jN-JJxpJs8Sszscm0',
    appId: '1:818820526373:android:6b526a45df19c1eeac2acc',
    messagingSenderId: '818820526373',
    projectId: 'notes-app-48cb7',
    storageBucket: 'notes-app-48cb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACHK_41vj3Z_aLIuhwFdBmxahK0f958D8',
    appId: '1:818820526373:ios:895f61af42dd00a5ac2acc',
    messagingSenderId: '818820526373',
    projectId: 'notes-app-48cb7',
    storageBucket: 'notes-app-48cb7.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACHK_41vj3Z_aLIuhwFdBmxahK0f958D8',
    appId: '1:818820526373:ios:895f61af42dd00a5ac2acc',
    messagingSenderId: '818820526373',
    projectId: 'notes-app-48cb7',
    storageBucket: 'notes-app-48cb7.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtOZH0YZroH6cZu3RYBF8PlvQYAJqR30g',
    appId: '1:818820526373:web:814053116fc0f9b1ac2acc',
    messagingSenderId: '818820526373',
    projectId: 'notes-app-48cb7',
    authDomain: 'notes-app-48cb7.firebaseapp.com',
    storageBucket: 'notes-app-48cb7.appspot.com',
  );

}